package timezones

// Source https://github.com/dmfilipenko/timezones.json
var goData = []TimeZone{
	{
		Value:  "Dateline Standard Time",
		Abbr:   "DST",
		Offset: -12,
		Isdst:  false,
		Text:   "(UTC-12:00) International Date Line West",
		Utc: []string{
			"Etc/GMT+12",
		},
	},
	{
		Value:  "UTC-11",
		Abbr:   "U",
		Offset: -11,
		Isdst:  false,
		Text:   "(UTC-11:00) Coordinated Universal Time-11",
		Utc: []string{
			"Etc/GMT+11",
			"Pacific/Midway",
			"Pacific/Niue",
			"Pacific/Pago_Pago",
		},
	},
	{
		Value:  "Hawaiian Standard Time",
		Abbr:   "HST",
		Offset: -10,
		Isdst:  false,
		Text:   "(UTC-10:00) Hawaii",
		Utc: []string{
			"Etc/GMT+10",
			"Pacific/Honolulu",
			"Pacific/Johnston",
			"Pacific/Rarotonga",
			"Pacific/Tahiti",
		},
	},
	{
		Value:  "Alaskan Standard Time",
		Abbr:   "AKDT",
		Offset: -8,
		Isdst:  true,
		Text:   "(UTC-09:00) Alaska",
		Utc: []string{
			"America/Anchorage",
			"America/Juneau",
			"America/Nome",
			"America/Sitka",
			"America/Yakutat",
		},
	},
	{
		Value:  "Pacific Standard Time (Mexico)",
		Abbr:   "PDT",
		Offset: -7,
		Isdst:  true,
		Text:   "(UTC-08:00) Baja California",
		Utc: []string{
			"America/Santa_Isabel",
		},
	},
	{
		Value:  "Pacific Daylight Time",
		Abbr:   "PDT",
		Offset: -7,
		Isdst:  true,
		Text:   "(UTC-07:00) Pacific Time (US & Canada)",
		Utc: []string{
			"America/Dawson",
			"America/Los_Angeles",
			"America/Tijuana",
			"America/Vancouver",
			"America/Whitehorse",
		},
	},
	{
		Value:  "Pacific Standard Time",
		Abbr:   "PST",
		Offset: -8,
		Isdst:  false,
		Text:   "(UTC-08:00) Pacific Time (US & Canada)",
		Utc: []string{
			"America/Dawson",
			"America/Los_Angeles",
			"America/Tijuana",
			"America/Vancouver",
			"America/Whitehorse",
			"PST8PDT",
		},
	},
	{
		Value:  "US Mountain Standard Time",
		Abbr:   "UMST",
		Offset: -7,
		Isdst:  false,
		Text:   "(UTC-07:00) Arizona",
		Utc: []string{
			"America/Creston",
			"America/Dawson_Creek",
			"America/Hermosillo",
			"America/Phoenix",
			"Etc/GMT+7",
		},
	},
	{
		Value:  "Mountain Standard Time (Mexico)",
		Abbr:   "MDT",
		Offset: -6,
		Isdst:  true,
		Text:   "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
		Utc: []string{
			"America/Chihuahua",
			"America/Mazatlan",
		},
	},
	{
		Value:  "Mountain Standard Time",
		Abbr:   "MDT",
		Offset: -6,
		Isdst:  true,
		Text:   "(UTC-07:00) Mountain Time (US & Canada)",
		Utc: []string{
			"America/Boise",
			"America/Cambridge_Bay",
			"America/Denver",
			"America/Edmonton",
			"America/Inuvik",
			"America/Ojinaga",
			"America/Yellowknife",
			"MST7MDT",
		},
	},
	{
		Value:  "Central America Standard Time",
		Abbr:   "CAST",
		Offset: -6,
		Isdst:  false,
		Text:   "(UTC-06:00) Central America",
		Utc: []string{
			"America/Belize",
			"America/Costa_Rica",
			"America/El_Salvador",
			"America/Guatemala",
			"America/Managua",
			"America/Tegucigalpa",
			"Etc/GMT+6",
			"Pacific/Galapagos",
		},
	},
	{
		Value:  "Central Standard Time",
		Abbr:   "CDT",
		Offset: -5,
		Isdst:  true,
		Text:   "(UTC-06:00) Central Time (US & Canada)",
		Utc: []string{
			"America/Chicago",
			"America/Indiana/Knox",
			"America/Indiana/Tell_City",
			"America/Matamoros",
			"America/Menominee",
			"America/North_Dakota/Beulah",
			"America/North_Dakota/Center",
			"America/North_Dakota/New_Salem",
			"America/Rainy_River",
			"America/Rankin_Inlet",
			"America/Resolute",
			"America/Winnipeg",
			"CST6CDT",
		},
	},
	{
		Value:  "Central Standard Time (Mexico)",
		Abbr:   "CDT",
		Offset: -5,
		Isdst:  true,
		Text:   "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
		Utc: []string{
			"America/Bahia_Banderas",
			"America/Cancun",
			"America/Merida",
			"America/Mexico_City",
			"America/Monterrey",
		},
	},
	{
		Value:  "Canada Central Standard Time",
		Abbr:   "CCST",
		Offset: -6,
		Isdst:  false,
		Text:   "(UTC-06:00) Saskatchewan",
		Utc: []string{
			"America/Regina",
			"America/Swift_Current",
		},
	},
	{
		Value:  "SA Pacific Standard Time",
		Abbr:   "SPST",
		Offset: -5,
		Isdst:  false,
		Text:   "(UTC-05:00) Bogota, Lima, Quito",
		Utc: []string{
			"America/Bogota",
			"America/Cayman",
			"America/Coral_Harbour",
			"America/Eirunepe",
			"America/Guayaquil",
			"America/Jamaica",
			"America/Lima",
			"America/Panama",
			"America/Rio_Branco",
			"Etc/GMT+5",
		},
	},
	{
		Value:  "Eastern Standard Time",
		Abbr:   "EDT",
		Offset: -4,
		Isdst:  true,
		Text:   "(UTC-05:00) Eastern Time (US & Canada)",
		Utc: []string{
			"America/Detroit",
			"America/Havana",
			"America/Indiana/Petersburg",
			"America/Indiana/Vincennes",
			"America/Indiana/Winamac",
			"America/Iqaluit",
			"America/Kentucky/Monticello",
			"America/Louisville",
			"America/Montreal",
			"America/Nassau",
			"America/New_York",
			"America/Nipigon",
			"America/Pangnirtung",
			"America/Port-au-Prince",
			"America/Thunder_Bay",
			"America/Toronto",
			"EST5EDT",
		},
	},
	{
		Value:  "US Eastern Standard Time",
		Abbr:   "UEDT",
		Offset: -4,
		Isdst:  true,
		Text:   "(UTC-05:00) Indiana (East)",
		Utc: []string{
			"America/Indiana/Marengo",
			"America/Indiana/Vevay",
			"America/Indianapolis",
		},
	},
	{
		Value:  "Venezuela Standard Time",
		Abbr:   "VST",
		Offset: -4.5,
		Isdst:  false,
		Text:   "(UTC-04:30) Caracas",
		Utc: []string{
			"America/Caracas",
		},
	},
	{
		Value:  "Paraguay Standard Time",
		Abbr:   "PYT",
		Offset: -4,
		Isdst:  false,
		Text:   "(UTC-04:00) Asuncion",
		Utc: []string{
			"America/Asuncion",
		},
	},
	{
		Value:  "Atlantic Standard Time",
		Abbr:   "ADT",
		Offset: -3,
		Isdst:  true,
		Text:   "(UTC-04:00) Atlantic Time (Canada)",
		Utc: []string{
			"America/Glace_Bay",
			"America/Goose_Bay",
			"America/Halifax",
			"America/Moncton",
			"America/Thule",
			"Atlantic/Bermuda",
		},
	},
	{
		Value:  "Central Brazilian Standard Time",
		Abbr:   "CBST",
		Offset: -4,
		Isdst:  false,
		Text:   "(UTC-04:00) Cuiaba",
		Utc: []string{
			"America/Campo_Grande",
			"America/Cuiaba",
		},
	},
	{
		Value:  "SA Western Standard Time",
		Abbr:   "SWST",
		Offset: -4,
		Isdst:  false,
		Text:   "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
		Utc: []string{
			"America/Anguilla",
			"America/Antigua",
			"America/Aruba",
			"America/Barbados",
			"America/Blanc-Sablon",
			"America/Boa_Vista",
			"America/Curacao",
			"America/Dominica",
			"America/Grand_Turk",
			"America/Grenada",
			"America/Guadeloupe",
			"America/Guyana",
			"America/Kralendijk",
			"America/La_Paz",
			"America/Lower_Princes",
			"America/Manaus",
			"America/Marigot",
			"America/Martinique",
			"America/Montserrat",
			"America/Port_of_Spain",
			"America/Porto_Velho",
			"America/Puerto_Rico",
			"America/Santo_Domingo",
			"America/St_Barthelemy",
			"America/St_Kitts",
			"America/St_Lucia",
			"America/St_Thomas",
			"America/St_Vincent",
			"America/Tortola",
			"Etc/GMT+4",
		},
	},
	{
		Value:  "Pacific SA Standard Time",
		Abbr:   "PSST",
		Offset: -4,
		Isdst:  false,
		Text:   "(UTC-04:00) Santiago",
		Utc: []string{
			"America/Santiago",
			"Antarctica/Palmer",
		},
	},
	{
		Value:  "Newfoundland Standard Time",
		Abbr:   "NDT",
		Offset: -2.5,
		Isdst:  true,
		Text:   "(UTC-03:30) Newfoundland",
		Utc: []string{
			"America/St_Johns",
		},
	},
	{
		Value:  "E. South America Standard Time",
		Abbr:   "ESAST",
		Offset: -3,
		Isdst:  false,
		Text:   "(UTC-03:00) Brasilia",
		Utc: []string{
			"America/Sao_Paulo",
		},
	},
	{
		Value:  "Argentina Standard Time",
		Abbr:   "AST",
		Offset: -3,
		Isdst:  false,
		Text:   "(UTC-03:00) Buenos Aires",
		Utc: []string{
			"America/Argentina/La_Rioja",
			"America/Argentina/Rio_Gallegos",
			"America/Argentina/Salta",
			"America/Argentina/San_Juan",
			"America/Argentina/San_Luis",
			"America/Argentina/Tucuman",
			"America/Argentina/Ushuaia",
			"America/Buenos_Aires",
			"America/Catamarca",
			"America/Cordoba",
			"America/Jujuy",
			"America/Mendoza",
		},
	},
	{
		Value:  "SA Eastern Standard Time",
		Abbr:   "SEST",
		Offset: -3,
		Isdst:  false,
		Text:   "(UTC-03:00) Cayenne, Fortaleza",
		Utc: []string{
			"America/Araguaina",
			"America/Belem",
			"America/Cayenne",
			"America/Fortaleza",
			"America/Maceio",
			"America/Paramaribo",
			"America/Recife",
			"America/Santarem",
			"Antarctica/Rothera",
			"Atlantic/Stanley",
			"Etc/GMT+3",
		},
	},
	{
		Value:  "Greenland Standard Time",
		Abbr:   "GDT",
		Offset: -3,
		Isdst:  true,
		Text:   "(UTC-03:00) Greenland",
		Utc: []string{
			"America/Godthab",
		},
	},
	{
		Value:  "Montevideo Standard Time",
		Abbr:   "MST",
		Offset: -3,
		Isdst:  false,
		Text:   "(UTC-03:00) Montevideo",
		Utc: []string{
			"America/Montevideo",
		},
	},
	{
		Value:  "Bahia Standard Time",
		Abbr:   "BST",
		Offset: -3,
		Isdst:  false,
		Text:   "(UTC-03:00) Salvador",
		Utc: []string{
			"America/Bahia",
		},
	},
	{
		Value:  "UTC-02",
		Abbr:   "U",
		Offset: -2,
		Isdst:  false,
		Text:   "(UTC-02:00) Coordinated Universal Time-02",
		Utc: []string{
			"America/Noronha",
			"Atlantic/South_Georgia",
			"Etc/GMT+2",
		},
	},
	{
		Value:  "Mid-Atlantic Standard Time",
		Abbr:   "MDT",
		Offset: -1,
		Isdst:  true,
		Text:   "(UTC-02:00) Mid-Atlantic - Old",
		Utc:    []string{},
	},
	{
		Value:  "Azores Standard Time",
		Abbr:   "ADT",
		Offset: 0,
		Isdst:  true,
		Text:   "(UTC-01:00) Azores",
		Utc: []string{
			"America/Scoresbysund",
			"Atlantic/Azores",
		},
	},
	{
		Value:  "Cape Verde Standard Time",
		Abbr:   "CVST",
		Offset: -1,
		Isdst:  false,
		Text:   "(UTC-01:00) Cape Verde Is.",
		Utc: []string{
			"Atlantic/Cape_Verde",
			"Etc/GMT+1",
		},
	},
	{
		Value:  "Morocco Standard Time",
		Abbr:   "MDT",
		Offset: 1,
		Isdst:  true,
		Text:   "(UTC) Casablanca",
		Utc: []string{
			"Africa/Casablanca",
			"Africa/El_Aaiun",
		},
	},
	{
		Value:  "UTC",
		Abbr:   "UTC",
		Offset: 0,
		Isdst:  false,
		Text:   "(UTC) Coordinated Universal Time",
		Utc: []string{
			"America/Danmarkshavn",
			"Etc/GMT",
		},
	},
	{
		Value:  "GMT Standard Time",
		Abbr:   "GMT",
		Offset: 0,
		Isdst:  false,
		Text:   "(UTC) Edinburgh, London",
		Utc: []string{
			"Europe/Isle_of_Man",
			"Europe/Guernsey",
			"Europe/Jersey",
			"Europe/London",
		},
	},
	{
		Value:  "British Summer Time",
		Abbr:   "BST",
		Offset: 1,
		Isdst:  true,
		Text:   "(UTC+01:00) Edinburgh, London",
		Utc: []string{
			"Europe/Isle_of_Man",
			"Europe/Guernsey",
			"Europe/Jersey",
			"Europe/London",
		},
	},
	{
		Value:  "GMT Standard Time",
		Abbr:   "GDT",
		Offset: 1,
		Isdst:  true,
		Text:   "(UTC) Dublin, Lisbon",
		Utc: []string{
			"Atlantic/Canary",
			"Atlantic/Faeroe",
			"Atlantic/Madeira",
			"Europe/Dublin",
			"Europe/Lisbon",
		},
	},
	{
		Value:  "Greenwich Standard Time",
		Abbr:   "GST",
		Offset: 0,
		Isdst:  false,
		Text:   "(UTC) Monrovia, Reykjavik",
		Utc: []string{
			"Africa/Abidjan",
			"Africa/Accra",
			"Africa/Bamako",
			"Africa/Banjul",
			"Africa/Bissau",
			"Africa/Conakry",
			"Africa/Dakar",
			"Africa/Freetown",
			"Africa/Lome",
			"Africa/Monrovia",
			"Africa/Nouakchott",
			"Africa/Ouagadougou",
			"Africa/Sao_Tome",
			"Atlantic/Reykjavik",
			"Atlantic/St_Helena",
		},
	},
	{
		Value:  "W. Europe Standard Time",
		Abbr:   "WEDT",
		Offset: 2,
		Isdst:  true,
		Text:   "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
		Utc: []string{
			"Arctic/Longyearbyen",
			"Europe/Amsterdam",
			"Europe/Andorra",
			"Europe/Berlin",
			"Europe/Busingen",
			"Europe/Gibraltar",
			"Europe/Luxembourg",
			"Europe/Malta",
			"Europe/Monaco",
			"Europe/Oslo",
			"Europe/Rome",
			"Europe/San_Marino",
			"Europe/Stockholm",
			"Europe/Vaduz",
			"Europe/Vatican",
			"Europe/Vienna",
			"Europe/Zurich",
		},
	},
	{
		Value:  "Central Europe Standard Time",
		Abbr:   "CEDT",
		Offset: 2,
		Isdst:  true,
		Text:   "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
		Utc: []string{
			"Europe/Belgrade",
			"Europe/Bratislava",
			"Europe/Budapest",
			"Europe/Ljubljana",
			"Europe/Podgorica",
			"Europe/Prague",
			"Europe/Tirane",
		},
	},
	{
		Value:  "Romance Standard Time",
		Abbr:   "RDT",
		Offset: 2,
		Isdst:  true,
		Text:   "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
		Utc: []string{
			"Africa/Ceuta",
			"Europe/Brussels",
			"Europe/Copenhagen",
			"Europe/Madrid",
			"Europe/Paris",
		},
	},
	{
		Value:  "Central European Standard Time",
		Abbr:   "CEDT",
		Offset: 2,
		Isdst:  true,
		Text:   "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
		Utc: []string{
			"Europe/Sarajevo",
			"Europe/Skopje",
			"Europe/Warsaw",
			"Europe/Zagreb",
		},
	},
	{
		Value:  "W. Central Africa Standard Time",
		Abbr:   "WCAST",
		Offset: 1,
		Isdst:  false,
		Text:   "(UTC+01:00) West Central Africa",
		Utc: []string{
			"Africa/Algiers",
			"Africa/Bangui",
			"Africa/Brazzaville",
			"Africa/Douala",
			"Africa/Kinshasa",
			"Africa/Lagos",
			"Africa/Libreville",
			"Africa/Luanda",
			"Africa/Malabo",
			"Africa/Ndjamena",
			"Africa/Niamey",
			"Africa/Porto-Novo",
			"Africa/Tunis",
			"Etc/GMT-1",
		},
	},
	{
		Value:  "Namibia Standard Time",
		Abbr:   "NST",
		Offset: 1,
		Isdst:  false,
		Text:   "(UTC+01:00) Windhoek",
		Utc: []string{
			"Africa/Windhoek",
		},
	},
	{
		Value:  "GTB Standard Time",
		Abbr:   "GDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) Athens, Bucharest",
		Utc: []string{
			"Asia/Nicosia",
			"Europe/Athens",
			"Europe/Bucharest",
			"Europe/Chisinau",
		},
	},
	{
		Value:  "Middle East Standard Time",
		Abbr:   "MEDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) Beirut",
		Utc: []string{
			"Asia/Beirut",
		},
	},
	{
		Value:  "Egypt Standard Time",
		Abbr:   "EST",
		Offset: 2,
		Isdst:  false,
		Text:   "(UTC+02:00) Cairo",
		Utc: []string{
			"Africa/Cairo",
		},
	},
	{
		Value:  "Syria Standard Time",
		Abbr:   "SDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) Damascus",
		Utc: []string{
			"Asia/Damascus",
		},
	},
	{
		Value:  "E. Europe Standard Time",
		Abbr:   "EEDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) E. Europe",
		Utc: []string{
			"Asia/Nicosia",
			"Europe/Athens",
			"Europe/Bucharest",
			"Europe/Chisinau",
			"Europe/Helsinki",
			"Europe/Kiev",
			"Europe/Mariehamn",
			"Europe/Nicosia",
			"Europe/Riga",
			"Europe/Sofia",
			"Europe/Tallinn",
			"Europe/Uzhgorod",
			"Europe/Vilnius",
			"Europe/Zaporozhye",
		},
	},
	{
		Value:  "South Africa Standard Time",
		Abbr:   "SAST",
		Offset: 2,
		Isdst:  false,
		Text:   "(UTC+02:00) Harare, Pretoria",
		Utc: []string{
			"Africa/Blantyre",
			"Africa/Bujumbura",
			"Africa/Gaborone",
			"Africa/Harare",
			"Africa/Johannesburg",
			"Africa/Kigali",
			"Africa/Lubumbashi",
			"Africa/Lusaka",
			"Africa/Maputo",
			"Africa/Maseru",
			"Africa/Mbabane",
			"Etc/GMT-2",
		},
	},
	{
		Value:  "FLE Standard Time",
		Abbr:   "FDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
		Utc: []string{
			"Europe/Helsinki",
			"Europe/Kiev",
			"Europe/Mariehamn",
			"Europe/Riga",
			"Europe/Sofia",
			"Europe/Tallinn",
			"Europe/Uzhgorod",
			"Europe/Vilnius",
			"Europe/Zaporozhye",
		},
	},
	{
		Value:  "Turkey Standard Time",
		Abbr:   "TDT",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Istanbul",
		Utc: []string{
			"Europe/Istanbul",
		},
	},
	{
		Value:  "Israel Standard Time",
		Abbr:   "JDT",
		Offset: 3,
		Isdst:  true,
		Text:   "(UTC+02:00) Jerusalem",
		Utc: []string{
			"Asia/Jerusalem",
		},
	},
	{
		Value:  "Libya Standard Time",
		Abbr:   "LST",
		Offset: 2,
		Isdst:  false,
		Text:   "(UTC+02:00) Tripoli",
		Utc: []string{
			"Africa/Tripoli",
		},
	},
	{
		Value:  "Jordan Standard Time",
		Abbr:   "JST",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Amman",
		Utc: []string{
			"Asia/Amman",
		},
	},
	{
		Value:  "Arabic Standard Time",
		Abbr:   "AST",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Baghdad",
		Utc: []string{
			"Asia/Baghdad",
		},
	},
	{
		Value:  "Kaliningrad Standard Time",
		Abbr:   "KST",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Kaliningrad, Minsk",
		Utc: []string{
			"Europe/Kaliningrad",
			"Europe/Minsk",
		},
	},
	{
		Value:  "Arab Standard Time",
		Abbr:   "AST",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Kuwait, Riyadh",
		Utc: []string{
			"Asia/Aden",
			"Asia/Bahrain",
			"Asia/Kuwait",
			"Asia/Qatar",
			"Asia/Riyadh",
		},
	},
	{
		Value:  "E. Africa Standard Time",
		Abbr:   "EAST",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Nairobi",
		Utc: []string{
			"Africa/Addis_Ababa",
			"Africa/Asmera",
			"Africa/Dar_es_Salaam",
			"Africa/Djibouti",
			"Africa/Juba",
			"Africa/Kampala",
			"Africa/Khartoum",
			"Africa/Mogadishu",
			"Africa/Nairobi",
			"Antarctica/Syowa",
			"Etc/GMT-3",
			"Indian/Antananarivo",
			"Indian/Comoro",
			"Indian/Mayotte",
		},
	},
	{
		Value:  "Moscow Standard Time",
		Abbr:   "MSK",
		Offset: 3,
		Isdst:  false,
		Text:   "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
		Utc: []string{
			"Europe/Kirov",
			"Europe/Moscow",
			"Europe/Simferopol",
			"Europe/Volgograd",
		},
	},
	{
		Value:  "Samara Time",
		Abbr:   "SAMT",
		Offset: 4,
		Isdst:  false,
		Text:   "(UTC+04:00) Samara, Ulyanovsk, Saratov",
		Utc: []string{
			"Europe/Astrakhan",
			"Europe/Samara",
			"Europe/Ulyanovsk",
		},
	},
	{
		Value:  "Iran Standard Time",
		Abbr:   "IDT",
		Offset: 4.5,
		Isdst:  true,
		Text:   "(UTC+03:30) Tehran",
		Utc: []string{
			"Asia/Tehran",
		},
	},
	{
		Value:  "Arabian Standard Time",
		Abbr:   "AST",
		Offset: 4,
		Isdst:  false,
		Text:   "(UTC+04:00) Abu Dhabi, Muscat",
		Utc: []string{
			"Asia/Dubai",
			"Asia/Muscat",
			"Etc/GMT-4",
		},
	},
	{
		Value:  "Azerbaijan Standard Time",
		Abbr:   "ADT",
		Offset: 5,
		Isdst:  true,
		Text:   "(UTC+04:00) Baku",
		Utc: []string{
			"Asia/Baku",
		},
	},
	{
		Value:  "Mauritius Standard Time",
		Abbr:   "MST",
		Offset: 4,
		Isdst:  false,
		Text:   "(UTC+04:00) Port Louis",
		Utc: []string{
			"Indian/Mahe",
			"Indian/Mauritius",
			"Indian/Reunion",
		},
	},
	{
		Value:  "Georgian Standard Time",
		Abbr:   "GET",
		Offset: 4,
		Isdst:  false,
		Text:   "(UTC+04:00) Tbilisi",
		Utc: []string{
			"Asia/Tbilisi",
		},
	},
	{
		Value:  "Caucasus Standard Time",
		Abbr:   "CST",
		Offset: 4,
		Isdst:  false,
		Text:   "(UTC+04:00) Yerevan",
		Utc: []string{
			"Asia/Yerevan",
		},
	},
	{
		Value:  "Afghanistan Standard Time",
		Abbr:   "AST",
		Offset: 4.5,
		Isdst:  false,
		Text:   "(UTC+04:30) Kabul",
		Utc: []string{
			"Asia/Kabul",
		},
	},
	{
		Value:  "West Asia Standard Time",
		Abbr:   "WAST",
		Offset: 5,
		Isdst:  false,
		Text:   "(UTC+05:00) Ashgabat, Tashkent",
		Utc: []string{
			"Antarctica/Mawson",
			"Asia/Aqtau",
			"Asia/Aqtobe",
			"Asia/Ashgabat",
			"Asia/Dushanbe",
			"Asia/Oral",
			"Asia/Samarkand",
			"Asia/Tashkent",
			"Etc/GMT-5",
			"Indian/Kerguelen",
			"Indian/Maldives",
		},
	},
	{
		Value:  "Yekaterinburg Time",
		Abbr:   "YEKT",
		Offset: 5,
		Isdst:  false,
		Text:   "(UTC+05:00) Yekaterinburg",
		Utc: []string{
			"Asia/Yekaterinburg",
		},
	},
	{
		Value:  "Pakistan Standard Time",
		Abbr:   "PKT",
		Offset: 5,
		Isdst:  false,
		Text:   "(UTC+05:00) Islamabad, Karachi",
		Utc: []string{
			"Asia/Karachi",
		},
	},
	{
		Value:  "India Standard Time",
		Abbr:   "IST",
		Offset: 5.5,
		Isdst:  false,
		Text:   "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
		Utc: []string{
			"Asia/Kolkata",
		},
	},
	{
		Value:  "Sri Lanka Standard Time",
		Abbr:   "SLST",
		Offset: 5.5,
		Isdst:  false,
		Text:   "(UTC+05:30) Sri Jayawardenepura",
		Utc: []string{
			"Asia/Colombo",
		},
	},
	{
		Value:  "Nepal Standard Time",
		Abbr:   "NST",
		Offset: 5.75,
		Isdst:  false,
		Text:   "(UTC+05:45) Kathmandu",
		Utc: []string{
			"Asia/Kathmandu",
		},
	},
	{
		Value:  "Central Asia Standard Time",
		Abbr:   "CAST",
		Offset: 6,
		Isdst:  false,
		Text:   "(UTC+06:00) Astana",
		Utc: []string{
			"Antarctica/Vostok",
			"Asia/Almaty",
			"Asia/Bishkek",
			"Asia/Qyzylorda",
			"Asia/Urumqi",
			"Etc/GMT-6",
			"Indian/Chagos",
		},
	},
	{
		Value:  "Bangladesh Standard Time",
		Abbr:   "BST",
		Offset: 6,
		Isdst:  false,
		Text:   "(UTC+06:00) Dhaka",
		Utc: []string{
			"Asia/Dhaka",
			"Asia/Thimphu",
		},
	},
	{
		Value:  "Myanmar Standard Time",
		Abbr:   "MST",
		Offset: 6.5,
		Isdst:  false,
		Text:   "(UTC+06:30) Yangon (Rangoon)",
		Utc: []string{
			"Asia/Rangoon",
			"Indian/Cocos",
		},
	},
	{
		Value:  "SE Asia Standard Time",
		Abbr:   "SAST",
		Offset: 7,
		Isdst:  false,
		Text:   "(UTC+07:00) Bangkok, Hanoi, Jakarta",
		Utc: []string{
			"Antarctica/Davis",
			"Asia/Bangkok",
			"Asia/Hovd",
			"Asia/Jakarta",
			"Asia/Phnom_Penh",
			"Asia/Pontianak",
			"Asia/Saigon",
			"Asia/Vientiane",
			"Etc/GMT-7",
			"Indian/Christmas",
		},
	},
	{
		Value:  "N. Central Asia Standard Time",
		Abbr:   "NCAST",
		Offset: 7,
		Isdst:  false,
		Text:   "(UTC+07:00) Novosibirsk",
		Utc: []string{
			"Asia/Novokuznetsk",
			"Asia/Novosibirsk",
			"Asia/Omsk",
		},
	},
	{
		Value:  "China Standard Time",
		Abbr:   "CST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
		Utc: []string{
			"Asia/Hong_Kong",
			"Asia/Macau",
			"Asia/Shanghai",
		},
	},
	{
		Value:  "North Asia Standard Time",
		Abbr:   "NAST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Krasnoyarsk",
		Utc: []string{
			"Asia/Krasnoyarsk",
		},
	},
	{
		Value:  "Singapore Standard Time",
		Abbr:   "MPST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Kuala Lumpur, Singapore",
		Utc: []string{
			"Asia/Brunei",
			"Asia/Kuala_Lumpur",
			"Asia/Kuching",
			"Asia/Makassar",
			"Asia/Manila",
			"Asia/Singapore",
			"Etc/GMT-8",
		},
	},
	{
		Value:  "W. Australia Standard Time",
		Abbr:   "WAST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Perth",
		Utc: []string{
			"Antarctica/Casey",
			"Australia/Perth",
		},
	},
	{
		Value:  "Taipei Standard Time",
		Abbr:   "TST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Taipei",
		Utc: []string{
			"Asia/Taipei",
		},
	},
	{
		Value:  "Ulaanbaatar Standard Time",
		Abbr:   "UST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Ulaanbaatar",
		Utc: []string{
			"Asia/Choibalsan",
			"Asia/Ulaanbaatar",
		},
	},
	{
		Value:  "North Asia East Standard Time",
		Abbr:   "NAEST",
		Offset: 8,
		Isdst:  false,
		Text:   "(UTC+08:00) Irkutsk",
		Utc: []string{
			"Asia/Irkutsk",
		},
	},
	{
		Value:  "Japan Standard Time",
		Abbr:   "JST",
		Offset: 9,
		Isdst:  false,
		Text:   "(UTC+09:00) Osaka, Sapporo, Tokyo",
		Utc: []string{
			"Asia/Dili",
			"Asia/Jayapura",
			"Asia/Tokyo",
			"Etc/GMT-9",
			"Pacific/Palau",
		},
	},
	{
		Value:  "Korea Standard Time",
		Abbr:   "KST",
		Offset: 9,
		Isdst:  false,
		Text:   "(UTC+09:00) Seoul",
		Utc: []string{
			"Asia/Pyongyang",
			"Asia/Seoul",
		},
	},
	{
		Value:  "Cen. Australia Standard Time",
		Abbr:   "CAST",
		Offset: 9.5,
		Isdst:  false,
		Text:   "(UTC+09:30) Adelaide",
		Utc: []string{
			"Australia/Adelaide",
			"Australia/Broken_Hill",
		},
	},
	{
		Value:  "AUS Central Standard Time",
		Abbr:   "ACST",
		Offset: 9.5,
		Isdst:  false,
		Text:   "(UTC+09:30) Darwin",
		Utc: []string{
			"Australia/Darwin",
		},
	},
	{
		Value:  "E. Australia Standard Time",
		Abbr:   "EAST",
		Offset: 10,
		Isdst:  false,
		Text:   "(UTC+10:00) Brisbane",
		Utc: []string{
			"Australia/Brisbane",
			"Australia/Lindeman",
		},
	},
	{
		Value:  "AUS Eastern Standard Time",
		Abbr:   "AEST",
		Offset: 10,
		Isdst:  false,
		Text:   "(UTC+10:00) Canberra, Melbourne, Sydney",
		Utc: []string{
			"Australia/Melbourne",
			"Australia/Sydney",
		},
	},
	{
		Value:  "West Pacific Standard Time",
		Abbr:   "WPST",
		Offset: 10,
		Isdst:  false,
		Text:   "(UTC+10:00) Guam, Port Moresby",
		Utc: []string{
			"Antarctica/DumontDUrville",
			"Etc/GMT-10",
			"Pacific/Guam",
			"Pacific/Port_Moresby",
			"Pacific/Saipan",
			"Pacific/Truk",
		},
	},
	{
		Value:  "Tasmania Standard Time",
		Abbr:   "TST",
		Offset: 10,
		Isdst:  false,
		Text:   "(UTC+10:00) Hobart",
		Utc: []string{
			"Australia/Currie",
			"Australia/Hobart",
		},
	},
	{
		Value:  "Yakutsk Standard Time",
		Abbr:   "YST",
		Offset: 9,
		Isdst:  false,
		Text:   "(UTC+09:00) Yakutsk",
		Utc: []string{
			"Asia/Chita",
			"Asia/Khandyga",
			"Asia/Yakutsk",
		},
	},
	{
		Value:  "Central Pacific Standard Time",
		Abbr:   "CPST",
		Offset: 11,
		Isdst:  false,
		Text:   "(UTC+11:00) Solomon Is., New Caledonia",
		Utc: []string{
			"Antarctica/Macquarie",
			"Etc/GMT-11",
			"Pacific/Efate",
			"Pacific/Guadalcanal",
			"Pacific/Kosrae",
			"Pacific/Noumea",
			"Pacific/Ponape",
		},
	},
	{
		Value:  "Vladivostok Standard Time",
		Abbr:   "VST",
		Offset: 11,
		Isdst:  false,
		Text:   "(UTC+11:00) Vladivostok",
		Utc: []string{
			"Asia/Sakhalin",
			"Asia/Ust-Nera",
			"Asia/Vladivostok",
		},
	},
	{
		Value:  "New Zealand Standard Time",
		Abbr:   "NZST",
		Offset: 12,
		Isdst:  false,
		Text:   "(UTC+12:00) Auckland, Wellington",
		Utc: []string{
			"Antarctica/McMurdo",
			"Pacific/Auckland",
		},
	},
	{
		Value:  "UTC+12",
		Abbr:   "U",
		Offset: 12,
		Isdst:  false,
		Text:   "(UTC+12:00) Coordinated Universal Time+12",
		Utc: []string{
			"Etc/GMT-12",
			"Pacific/Funafuti",
			"Pacific/Kwajalein",
			"Pacific/Majuro",
			"Pacific/Nauru",
			"Pacific/Tarawa",
			"Pacific/Wake",
			"Pacific/Wallis",
		},
	},
	{
		Value:  "Fiji Standard Time",
		Abbr:   "FST",
		Offset: 12,
		Isdst:  false,
		Text:   "(UTC+12:00) Fiji",
		Utc: []string{
			"Pacific/Fiji",
		},
	},
	{
		Value:  "Magadan Standard Time",
		Abbr:   "MST",
		Offset: 12,
		Isdst:  false,
		Text:   "(UTC+12:00) Magadan",
		Utc: []string{
			"Asia/Anadyr",
			"Asia/Kamchatka",
			"Asia/Magadan",
			"Asia/Srednekolymsk",
		},
	},
	{
		Value:  "Kamchatka Standard Time",
		Abbr:   "KDT",
		Offset: 13,
		Isdst:  true,
		Text:   "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
		Utc: []string{
			"Asia/Kamchatka",
		},
	},
	{
		Value:  "Tonga Standard Time",
		Abbr:   "TST",
		Offset: 13,
		Isdst:  false,
		Text:   "(UTC+13:00) Nuku'alofa",
		Utc: []string{
			"Etc/GMT-13",
			"Pacific/Enderbury",
			"Pacific/Fakaofo",
			"Pacific/Tongatapu",
		},
	},
	{
		Value:  "Samoa Standard Time",
		Abbr:   "SST",
		Offset: 13,
		Isdst:  false,
		Text:   "(UTC+13:00) Samoa",
		Utc: []string{
			"Pacific/Apia",
		},
	},
}
